### ISSUE TITLE
IOError: [Errno 22] invalid mode ('rb') or filename

### ISSUE THREAD

**Issue by kyscg** [luisbatalha/prime_motion_picture#2]
Any idea how to fix this? I tried [this](https://python-forum.io/Thread-Errno-22-Invalid-argument). Didn't work...

```
$ python get_prime.py ["C:/B.jpeg"] {426} {532}
  Traceback (most recent call last):
    File "get_prime.py", line 66, in <module>
      img = Image.open(basefn)
    File "C:\Users\GANDHI\Anaconda3\lib\site-packages\PIL\Image.py", line 2543, in open
      fp = builtins.open(filename, "rb")
  OSError: [Errno 22] Invalid argument: '[C:/B.jpeg]'
```

**Comment by kyscg** [comment]
Nice work btw, really liked it @luisbatalha

**Comment by luisbatalha** [comment]
The way you'd run it would be: python get_prime.py B.jpeg 426 532

**Comment by kyscg** [comment]
Thanks
